<?php

use Magento\Framework\App\ObjectManager;
use Dialcom\Przelewy\Controller\Przelewy\Summary;
use Dialcom\Przelewy\Przelewy24Class;

$objectManager = ObjectManager::getInstance();
$order_id = $this->getRequest()->getParam('order_id');
$order = $objectManager->create('Magento\Sales\Model\Order')->load($order_id);
if ($order && $order->getBaseTotalDue() > 0 && in_array($order->getStatus(), ['pending', Przelewy24Class::PENDING_PAYMENT_CUSTOM_STATUS])) {
    ?>

    <div style="text-align: right">
    <div class="buttons-set">
        <p>
            <a href="<?php echo Summary::getLink($order) ?>">
                <?php echo __('Pay with Przelewy24') ?>
            </a>
        </p>
    </div>

    <?php
}
